// Generated by authoring/author-plaza-facades.py. Do not hand-edit geometry.
// Original unfinished vector art; every vertex uses the exact 128 x 64 projection.
// All points/bounds are world-relative to contact, PNG dimensions are source pixels.
// Foundation and upper share an exact 2 px/world export frame and contact pivot.
export const TOWN_FACADES = [
  {
    "id": "rear",
    "contact": {
      "x": 1496,
      "y": 432
    },
    "footprint": [
      {
        "x": -256,
        "y": -128
      },
      {
        "x": -192,
        "y": -160
      },
      {
        "x": 64,
        "y": -32
      },
      {
        "x": 0,
        "y": 0
      }
    ],
    "upperPolygons": [
      [
        {
          "x": 64,
          "y": -40
        },
        {
          "x": 0,
          "y": -8
        },
        {
          "x": 0,
          "y": -96
        },
        {
          "x": 64,
          "y": -128
        }
      ],
      [
        {
          "x": -256,
          "y": -136
        },
        {
          "x": 0,
          "y": -8
        },
        {
          "x": 0,
          "y": -96
        },
        {
          "x": -256,
          "y": -224
        }
      ],
      [
        {
          "x": 64,
          "y": -128
        },
        {
          "x": 0,
          "y": -96
        },
        {
          "x": 32.0,
          "y": -136.0
        }
      ],
      [
        {
          "x": -192,
          "y": -256
        },
        {
          "x": 64,
          "y": -128
        },
        {
          "x": 32.0,
          "y": -136.0
        },
        {
          "x": -224.0,
          "y": -264.0
        }
      ],
      [
        {
          "x": -224.0,
          "y": -264.0
        },
        {
          "x": 32.0,
          "y": -136.0
        },
        {
          "x": 0,
          "y": -96
        },
        {
          "x": -256,
          "y": -224
        }
      ]
    ],
    "layers": {
      "foundation": {
        "key": "town_plaza_rear_foundation_v1",
        "url": "/games/arpg/town-plaza-v1/town_plaza_rear_foundation_v1.png",
        "originX": 0.7926829268292683,
        "originY": 0.9852941176470589,
        "scale": 0.5,
        "width": 656,
        "height": 544
      },
      "upper": {
        "key": "town_plaza_rear_upper_v1",
        "url": "/games/arpg/town-plaza-v1/town_plaza_rear_upper_v1.png",
        "originX": 0.7926829268292683,
        "originY": 0.9852941176470589,
        "scale": 0.5,
        "width": 656,
        "height": 544
      }
    },
    "drawnBounds": {
      "minX": -256.3,
      "minY": -264.3,
      "maxX": 64.3,
      "maxY": 0.3
    }
  },
  {
    "id": "endcap",
    "contact": {
      "x": 1728,
      "y": 376
    },
    "footprint": [
      {
        "x": 0,
        "y": 0
      },
      {
        "x": 256,
        "y": -128
      },
      {
        "x": 192,
        "y": -160
      },
      {
        "x": -64,
        "y": -32
      }
    ],
    "upperPolygons": [
      [
        {
          "x": -64,
          "y": -40
        },
        {
          "x": 0,
          "y": -8
        },
        {
          "x": 0,
          "y": -72
        },
        {
          "x": -64,
          "y": -104
        }
      ],
      [
        {
          "x": 256,
          "y": -136
        },
        {
          "x": 0,
          "y": -8
        },
        {
          "x": 0,
          "y": -72
        },
        {
          "x": 256,
          "y": -200
        }
      ],
      [
        {
          "x": -64,
          "y": -104
        },
        {
          "x": 0,
          "y": -72
        },
        {
          "x": -32.0,
          "y": -104.0
        }
      ],
      [
        {
          "x": 192,
          "y": -232
        },
        {
          "x": -64,
          "y": -104
        },
        {
          "x": -32.0,
          "y": -104.0
        },
        {
          "x": 224.0,
          "y": -232.0
        }
      ],
      [
        {
          "x": 224.0,
          "y": -232.0
        },
        {
          "x": -32.0,
          "y": -104.0
        },
        {
          "x": 0,
          "y": -72
        },
        {
          "x": 256,
          "y": -200
        }
      ]
    ],
    "layers": {
      "foundation": {
        "key": "town_plaza_endcap_foundation_v1",
        "url": "/games/arpg/town-plaza-v1/town_plaza_endcap_foundation_v1.png",
        "originX": 0.2073170731707317,
        "originY": 0.9833333333333333,
        "scale": 0.5,
        "width": 656,
        "height": 480
      },
      "upper": {
        "key": "town_plaza_endcap_upper_v1",
        "url": "/games/arpg/town-plaza-v1/town_plaza_endcap_upper_v1.png",
        "originX": 0.2073170731707317,
        "originY": 0.9833333333333333,
        "scale": 0.5,
        "width": 656,
        "height": 480
      }
    },
    "drawnBounds": {
      "minX": -64.3,
      "minY": -232.3,
      "maxX": 256.3,
      "maxY": 0.3
    }
  }
] as const;
