#!/usr/bin/env python3
"""Deterministic crop/resize/compression only. All illustration comes from recorded imagegen or canonical sources."""
import hashlib
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'art-source/games/runner/lanternway/v1'
OUTPUT = ROOT / 'static/games/runner/skins/lanternway'
OUTPUT.mkdir(parents=True, exist_ok=True)
manifest = {'version': 1, 'type': 'cosmetic-only', 'generator': 'built-in imagegen; canonical character frames reused without repainting', 'assets': {}}

def digest(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()

def save(name, image, source, **extra):
    path = OUTPUT / f'{name}.webp'
    image.save(path, 'WEBP', quality=88, method=6, exact=True)
    manifest['assets'][name] = {'url': f'/games/runner/skins/lanternway/{name}.webp', 'width': image.width, 'height': image.height, 'bytes': path.stat().st_size, 'sha256': digest(path), 'source': str(source.relative_to(ROOT)), 'sourceSha256': digest(source), **extra}

for name, size in [('background', (1280, 720)), ('ground', (1024, 342))]:
    source = SOURCE / f'{name}-master.png'
    save(name, Image.open(source).convert('RGB').resize(size, Image.Resampling.LANCZOS), source)

# Trim the generated eight-object board into a compact strip. Alpha >128 is used only
# to measure core bounds; original alpha is preserved, never recolored or redrawn.
source = SOURCE / 'props-master.png'
image = Image.open(source).convert('RGBA')
sheet = Image.new('RGBA', (1024, 128))
props = {}
names = ['waystone', 'shard', 'shield', 'magnet', 'doubleShards', 'slowMo', 'dash', 'dreamSurge']
for index, name in enumerate(names):
    col, row = index % 4, index // 4
    x1, x2 = col * image.width // 4, (col + 1) * image.width // 4
    y1, y2 = row * image.height // 2, (row + 1) * image.height // 2
    cell = image.crop((x1, y1, x2, y2))
    box = cell.getchannel('A').point(lambda a: 255 if a > 128 else 0).getbbox()
    if box is None:
        raise ValueError(f'Missing sprite: {name}')
    sprite = cell.crop(box)
    sprite.thumbnail((124, 124), Image.Resampling.LANCZOS)
    dx, dy = (128 - sprite.width) // 2, (128 - sprite.height) // 2
    sheet.alpha_composite(sprite, (index * 128 + dx, dy))
    props[name] = {'sourceRect': [index * 128 + dx, dy, sprite.width, sprite.height], 'masterCrop': [x1+box[0],y1+box[1],x1+box[2],y1+box[3]]}
save('props', sheet, source, sprites=props)

# The first twelve authored frames form the repeated east-facing walk cycle.
# All frames share a single union crop and feet baseline, preventing crop jitter.
for name, cell_size in [('adventurer', (64, 96)), ('echo', (80, 104))]:
    source = SOURCE / f'{name}-canonical-east-walk.png'
    original = Image.open(source).convert('RGBA')
    frames = [original.crop((i * 256, 0, (i+1) * 256, 256)) for i in range(12)]
    boxes = [f.getbbox() for f in frames]
    union = (min(b[0] for b in boxes), min(b[1] for b in boxes), max(b[2] for b in boxes), max(b[3] for b in boxes))
    cw, ch = cell_size
    scale = min(cw / (union[2]-union[0]), ch / (union[3]-union[1]))
    sw, sh = round((union[2]-union[0])*scale), round((union[3]-union[1])*scale)
    dx, dy = (cw-sw)//2, ch-sh
    strip = Image.new('RGBA', (cw * 12, ch))
    for index, frame in enumerate(frames):
        strip.alpha_composite(frame.crop(union).resize((sw, sh), Image.Resampling.LANCZOS), (index*cw+dx,dy))
    save(name, strip, source, frames=12, frameSize=[cw,ch], sourceRect=[dx,dy,sw,sh], sourceUnion=list(union), frameDurationMs=90)

manifest['totalRuntimeBytes'] = sum(a['bytes'] for a in manifest['assets'].values())
(OUTPUT / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
runtime = {key: {field: value for field, value in asset.items() if field in ('width', 'height', 'frames', 'frameSize', 'sourceRect', 'frameDurationMs')} for key, asset in manifest['assets'].items()}
runtime['props']['sprites'] = {key: value['sourceRect'] for key, value in props.items()}
(ROOT / 'src/lib/games/runnerLanternwayAtlas.ts').write_text('/** Generated by scripts/art/export-lanternway.py. Do not edit coordinates by hand. */\nexport const RUNNER_LANTERNWAY_ATLAS = ' + json.dumps(runtime, indent=2) + ' as const;\n')
print(json.dumps(manifest, indent=2))
