import { test, expect, calls, capture } from './guard';

test('REAL ENGINE: keyboard movement, pointer scaling, touch warp, pause and cleanup', async ({ page }, info) => {
  await page.goto('/app/games/dodge');
  await expect(page.getByTestId('orbfield-game')).toHaveAttribute('data-art-state', 'ready');
  expect(await page.evaluate(() => window.__orbfieldFixture.engine)).toBe('real');
  await page.getByRole('button', { name: 'Start round', exact: true }).click();
  const canvas = page.getByLabel('Orbfield play area', { exact: true });
  await expect(canvas).toHaveAttribute('tabindex', '0');
  await canvas.focus();
  await expect.poll(() => page.evaluate(() => window.__orbfieldFixture.engineState?.elapsedMs ?? 0)).toBeGreaterThan(0);
  const initialX = await page.evaluate(() => window.__orbfieldFixture.engineState!.playerX);
  await page.keyboard.down('ArrowRight');
  await expect.poll(() => page.evaluate(() => window.__orbfieldFixture.engineState!.playerX)).toBeGreaterThan(initialX + 5);
  await page.keyboard.up('ArrowRight');
  const bounds = await canvas.boundingBox();
  if (!bounds) throw new Error('Game canvas has no layout box.');
  await page.touchscreen.tap(bounds.x + bounds.width * 0.75, bounds.y + bounds.height * 0.75);
  const input = await canvas.evaluate((element: HTMLCanvasElement) => ({ width: element.width, height: element.height, state: window.__orbfieldFixture.engineState }));
  expect(input.state!.playerX).toBeCloseTo(input.width * 0.75, 0);
  expect(input.state!.playerY).toBeCloseTo(input.height * 0.75, 0);
  await page.getByRole('button', { name: /time warp/i }).tap();
  expect(await page.evaluate(() => window.__orbfieldFixture.engineState?.slowCharges)).toBe(2);
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Resume', exact: true })).toBeVisible();
  const paused = await page.evaluate(() => window.__orbfieldFixture.engineState!.elapsedMs);
  await page.waitForTimeout(200);
  expect(await page.evaluate(() => window.__orbfieldFixture.engineState!.elapsedMs)).toBe(paused);
  await capture(page, info, 'actual-engine-paused-after-input');
  await page.getByRole('button', { name: 'Resume', exact: true }).click();
  await expect.poll(() => page.evaluate(() => window.__orbfieldFixture.engineState!.elapsedMs)).toBeGreaterThan(paused);
  await page.getByRole('button', { name: /back to play/i }).first().click();
  await expect(page.getByRole('heading', { name: 'Play', exact: true })).toBeVisible();
  const ended = await page.evaluate(() => window.__orbfieldFixture.engineState!.elapsedMs);
  await page.waitForTimeout(100);
  expect(await page.evaluate(() => window.__orbfieldFixture.engineState!.elapsedMs)).toBe(ended);
  expect(await page.evaluate(() => window.__orbfieldFixture.engineEvents)).toContain('real:destroy');
  expect(await calls(page, 'start')).toHaveLength(1);
  expect(await calls(page, 'complete')).toHaveLength(0);
});
