/** Generated by scripts/art/export-lanternway.py. Do not edit coordinates by hand. */
export const RUNNER_LANTERNWAY_ATLAS = {
  "background": {
    "width": 1280,
    "height": 720
  },
  "ground": {
    "width": 1024,
    "height": 342
  },
  "props": {
    "width": 1024,
    "height": 128,
    "sprites": {
      "waystone": [
        20,
        2,
        87,
        124
      ],
      "shard": [
        157,
        2,
        70,
        124
      ],
      "shield": [
        278,
        2,
        84,
        124
      ],
      "magnet": [
        400,
        2,
        95,
        124
      ],
      "doubleShards": [
        523,
        2,
        106,
        124
      ],
      "slowMo": [
        667,
        2,
        74,
        124
      ],
      "dash": [
        784,
        2,
        95,
        124
      ],
      "dreamSurge": [
        913,
        2,
        94,
        124
      ]
    }
  },
  "adventurer": {
    "width": 768,
    "height": 96,
    "frames": 12,
    "frameSize": [
      64,
      96
    ],
    "sourceRect": [
      6,
      0,
      51,
      96
    ],
    "frameDurationMs": 90
  },
  "echo": {
    "width": 960,
    "height": 104,
    "frames": 12,
    "frameSize": [
      80,
      104
    ],
    "sourceRect": [
      1,
      0,
      77,
      104
    ],
    "frameDurationMs": 90
  }
} as const;
